(using ~(:util custom))

(def medium 'lg)
(def large "3xl")
(def largest (custom 2 'rem))

(def margin [:my 6])
(def inset [:p 12])
(def padding [:px 8 :py 3])
(def gap [:space-y 3])
(def back [:z 10])
(def front [:z 20])
(def frontmost [:z 30])
(def scaled-down [:scale 50])
(def square-size [:size (custom 60 'px)])
(def bar-width [:w (custom 60 'px)])
(def anchor [:bottom (custom 20 'px)])
